service: cal-fib-recur-1GB

frameworkVersion: ">=1.1.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs4.3

# following may not work, try from cmd: serverless deploy --region eu-west-1

functions:
  calcFibRecur1GB:
    handler: handler.endpoint
    events:
      - http:
          path: ping
          method: get
